# Generated by Django 4.2.4 on 2023-09-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concierge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=194, verbose_name="Nome Completo"),
                ),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
            ],
        ),
    ]
