# Generated by Django 4.2.2 on 2023-09-15 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("porteiros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concierge",
            options={"verbose_name": "Concierge", "verbose_name_plural": "Concierges"},
        ),
        migrations.AddField(
            model_name="concierge",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Data de Nascimento"),
        ),
        migrations.AddField(
            model_name="concierge",
            name="phone",
            field=models.CharField(
                max_length=11, null=True, verbose_name="Telefone de Contato"
            ),
        ),
        migrations.AddField(
            model_name="concierge",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="concierge",
            name="cpf",
            field=models.CharField(max_length=11, null=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="concierge",
            name="full_name",
            field=models.CharField(
                max_length=194, null=True, verbose_name="Nome Completo"
            ),
        ),
        migrations.AlterModelTable(
            name="concierge",
            table="concierge",
        ),
    ]
