# Generated by Django 4.2.4 on 2023-09-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("porteiros", "0003_alter_concierge_birth_date_alter_concierge_cpf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Nome completo"),
                ),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                ("birth_date", models.DateField(verbose_name="Data de nascimento")),
                (
                    "house_number",
                    models.PositiveBigIntegerField(
                        verbose_name="Número da casa a ser visitada"
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="Placa do veículo",
                    ),
                ),
                (
                    "arrival_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Horário de chegada na portaria",
                    ),
                ),
                (
                    "left_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Horário de saída da portaria",
                    ),
                ),
                (
                    "authorization_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Horário de autorização de entrada",
                    ),
                ),
                (
                    "responsible_resident",
                    models.CharField(
                        blank=True,
                        max_length=194,
                        verbose_name="Nome do morador responsável por autorizar a entrada do visitante",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="porteiros.concierge",
                        verbose_name="Responsável pelo registro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitor",
                "verbose_name_plural": "Visitors",
                "db_table": "visitor",
            },
        ),
    ]
