# Generated by Django 4.2.7 on 2023-11-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_rename_left_time_visitor_leave_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='house_number',
            field=models.PositiveSmallIntegerField(verbose_name='Número da casa a ser visitada'),
        ),
    ]
