# Generated by Django 4.2.7 on 2023-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_alter_visitor_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando autorização!'), ('EM_VISITA', 'Em visita!'), ('FINALIZADO', 'Visita Finalizada!')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
    ]
