# Generated by Django 4.2.7 on 2023-11-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_visitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando autorização'), ('EM_VISITA', 'Em visita'), ('FINALIZADO', 'Visita Finalizada')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
    ]
